# Create new window with 2x2 grid: prefix + G
bind G new-window \; split-window -h \; split-window -v \; select-pane -t 0 \; split-window -v \; select-pane -t 0

# Set the prefix to Ctrl+K
set -g prefix C-k

# Remove the old prefix
unbind C-b

# Send Ctrl+k to applications by pressing it twice
bind C-k send-prefix

# enable mouse scrolling
set -g mouse on
